### ISSUE TITLE
[Description] DiRT Directory link is outdated

### ISSUE THREAD

**Issue by JonathanReeve** [curateteaching/digitalpedagogy#22]
The link to the "Digital Research Tools Wiki," has, according to the site it links to, "been superseded by Bamboo DiRT." I'd recommend updating this link to http://dirtdirectory.org/. 

(As an aside, I don't fully understand how the DiRT directory is necessarily pedagogical in nature, i.e. that it "point[s] to a widespread emerging interest in digital pedagogy within digital humanities," but that's a matter for a peer comment, and not a bug report.)

**Comment by mkgold** [comment]
Thanks, Jonathan. Can you please let us know where this link appears so that we can correct it?  You are right that the URL you share above is the right one.

This project is collecting pedagogical artifacts -- resources of various kinds that are useful in teaching. Not all of those resources need to be pedagogical in and of themselves. That's why the DiRT directory fits well within this project.

Best

Matt

**Comment by JonathanReeve** [comment]
The link is in the first paragraph of the section "Conceptual Framing" from description.md. (I've started prefixing these issue reports with their associated keyword in brackets, since I can't quite figure out how to reference line numbers in GitHub in a way that's more useful for prose.) I'd be happy to correct this in my next PR, since I already have it open. 

That's a fair point about the DiRT directory. I agree that it's perfectly at home in the anthology as a whole. It still seems a little out-of-place to me in that particular sentence, only because it's cited as an example of an emerging interest in pedagogy, and it appears in a series of resources that are otherwise explicitly pedagogical in purpose.

**Comment by mkgold** [comment]
Thanks for fixing the link, Jonathan.
