### ISSUE TITLE
Recommended Citation

### ISSUE THREAD

**Issue by triproftri** [curateteaching/digitalpedagogy#28]
This is for Jonathan: a curator has requested that each entry have a "how to cite this entry" since we're doing something new and especially because each entry is in various states of review. We were going to come up with a way to do this. But, is there an MLA standard for versioning in citations?

**Comment by JonathanReeve** [comment]
This is a really interesting question, Kathy. I've asked around, but I'm unable to give a canonical answer, since our editorial department will likely have their own opinions about this when the volume reaches them for review. In the meantime, though, I've been told that the *MLA Handbook* section 5.7.18 is a good starting point, which uses the syntax "File last modified on 5 Apr. 2007." Then again, that section describes how to handle "digital files," which is treated differently in the *Handbook* from "web publications." 

I've been thinking about a way to cite particular revisions of a git-versioned publication, especially one which has multiple revisions per day, and I think we may be entering uncharted territory here. Although it's nonstandard, I really like the idea of including the seven-character git commit hash as a way of referencing a text at a particular stage of revision. Editorial has suggested that this could fit in the supplemental information section at the end of a citation, like this: 

>Davis, Rebecca, Matthew K. Gold, Katherine D. Harris, and Jentery Sayers, eds. *Digital Pedagogy in the Humanities: Concepts, Models, and Experiments*. Batch 1. *MLA Commons*. Web. 17 Feb. 2015. [Git commit 992e66d](https://github.com/curateteaching/digitalpedagogy/tree/992e66d1c3d7bce15eb6ad125d86d66b599c942d). 

This isn't MLA-ratified at all, but just a sketch for versioning notation. What I've done here is use the seven-character abbreviation of the git commit SHA, and linked that to the `<repo>/tree/<commit hash>`, so that the link takes you to a snapshot of the volume as it existed at that revision. 

Alternatively, you might be able to leverage [git tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) and achieve the same effect. For instance, you could `git tag` the current revision, 992e66d, as `Batch 1 Under Review`, or some other semantic edition label, and then you could use that as both an edition name (corresponding to how the *MLA Handbook* would cite "Second Edition," perhaps) and a revision ID, so that you could link to it like this: 

>Davis, Rebecca, Matthew K. Gold, Katherine D. Harris, and Jentery Sayers, eds. *Digital Pedagogy in the Humanities: Concepts, Models, and Experiments*. [Batch 1, Under Review](https://github.com/curateteaching/digitalpedagogy/tree/992e66d1c3d7bce15eb6ad125d86d66b599c942d). *MLA Commons*. Web. 17 Feb. 2015.

**Comment by mkgold** [comment]
This conversation is so fascinating. Thank you for helping us think through this, Jonathan!

**Comment by triproftri** [comment]
For clarity's sake, and for those who are not familiar with Github, the last citation method with "Batch 1, Under Review" might demonstrate most clearly to other readers of a citation at what stage this particular keyword was being quoted/cited. If that can get to the actual version as it was originally viewed -- because, yes, we are changing these quite rapidly. I suspect that these keyword entries will be revised again after open peer review.

**Comment by mkgold** [comment]
Great conversation but I think we can close this issue. If anyone needs/wants to reopen, please do.
